sonar.projectKey=planfuapi

sonar.projectName=planfuapi

sonar.projectVersion=1.0

sonar.projectBaseDir=.

sonar.sources=src/main/java

sonar.tests=src/test/java

sonar.java.binaries=target/classes

# SonarQube server

sonar.host.url=http://localhost:9000

sonar.token=sqp_28616d39877f01c5a0881e04373636ba8bd43cd5

# Encoding

sonar.sourceEncoding=UTF-8

# Coverage

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.junit.reportPaths=target/surefire-reports

# Exclusions/Inclusions

sonar.coverage.exclusions=**/config/**,**/dto/**,**/entity/**,**/exception/**,**/repository/**,**/Application*.java,**/UsersapiApplication.java
